// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBhiXyAlzHhqao9Tovz6gHcpyIIpFphEQ',
    appId: '1:718723788724:web:5af9276975b9e290664ce1',
    messagingSenderId: '718723788724',
    projectId: 'jp-food-3c9ed',
    authDomain: 'jp-food-3c9ed.firebaseapp.com',
    storageBucket: 'jp-food-3c9ed.firebasestorage.app',
    measurementId: 'G-QK4T7W8KFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bTEloNa3Ug4QvC_Fqpz8EarVD2pfvHk',
    appId: '1:718723788724:android:a50cb14db08c60a5664ce1',
    messagingSenderId: '718723788724',
    projectId: 'jp-food-3c9ed',
    storageBucket: 'jp-food-3c9ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhh5UHKfQJHPg46yWjxwthHnIgHk5KOUs',
    appId: '1:718723788724:ios:9af2020731df8558664ce1',
    messagingSenderId: '718723788724',
    projectId: 'jp-food-3c9ed',
    storageBucket: 'jp-food-3c9ed.firebasestorage.app',
    iosBundleId: 'com.example.empManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhh5UHKfQJHPg46yWjxwthHnIgHk5KOUs',
    appId: '1:718723788724:ios:9af2020731df8558664ce1',
    messagingSenderId: '718723788724',
    projectId: 'jp-food-3c9ed',
    storageBucket: 'jp-food-3c9ed.firebasestorage.app',
    iosBundleId: 'com.example.empManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBhiXyAlzHhqao9Tovz6gHcpyIIpFphEQ',
    appId: '1:718723788724:web:18bcdae4f69a26f8664ce1',
    messagingSenderId: '718723788724',
    projectId: 'jp-food-3c9ed',
    authDomain: 'jp-food-3c9ed.firebaseapp.com',
    storageBucket: 'jp-food-3c9ed.firebasestorage.app',
    measurementId: 'G-WMY2L7QVDW',
  );
}
